smov_config:
  ros__parameters:
    # It is important to change the back servos ports if you're using a single board.
    use_single_board: true

    # If use_single_board: false, then the second line is useless.
    front_board_i2c_bus: 4 #changed to 6 after burn through
    back_board_i2c_bus: 6

    #                      Port, Center, Range,   Direction, Default value on Start (Proportional), Base (centered) angle, Max angle (The highest angle possible relative to the trigonometry package)
    FRONT_BODY_LEFT:       [0,   330,    220,     -1,        0,                                     90,                    135]
    FRONT_BODY_RIGHT:      [15,  330,    220,     1,         0,                                     90,                    135]

    FRONT_UPPER_LEG_LEFT:  [1,   375,    310,     1,         0,                                     40,                    155]
    FRONT_UPPER_LEG_RIGHT: [14,  255,    310,     -1,        0,                                     40,                    155]

    FRONT_LOWER_LEG_LEFT:  [2,   320,    440,     1,        -1,                                     105,                   190]
    FRONT_LOWER_LEG_RIGHT: [13,  350,    440,     -1,        -1,                                    105,                   190]

    BACK_BODY_LEFT:        [7,   365,    220,     1,         0,                                     90,                    135]
    BACK_BODY_RIGHT:       [8,   360,    220,     -1,        0,                                     90,                    135]

    BACK_UPPER_LEG_LEFT:   [6,   350,    310,     1,         0,                                     40,                    155]
    BACK_UPPER_LEG_RIGHT:  [9,   380,    310,     -1,        0,                                     40,                    155]

    BACK_LOWER_LEG_LEFT:   [5,   380,    440,     1,         -1,                                    105,                   190]
    BACK_LOWER_LEG_RIGHT:  [10,   390,    440,     -1,        -1,                                    105,                   190]

smov_states:  
  ros__parameters:
    # The values are in centimeters.
    upper_leg_length: 14.0
    lower_leg_length: 14.0
    hip_body_distance: 4.0
    reset_vals_after_state_pkg_ended: true
