smov_config:
  ros__parameters:
    # It is important to change the back servos ports if you're using a single board.
    use_single_board: false

    # If use_single_board: false, then the second line is useless.
    front_board_i2c_bus: 1 #changed to 6 after burn through
    back_board_i2c_bus: 4

    #                      Port, Center, Range,   Direction, Default value on Start (Proportional), Base (centered) angle, Max angle (The highest angle possible relative to the trigonometry package)
    FRONT_BODY_LEFT:       [0,   295,    218,     -1,        0,                                     90,                    135]
    FRONT_BODY_RIGHT:      [15,  309,    210,     1,         0,                                     90,                    135]

    FRONT_UPPER_LEG_LEFT:  [1,   376,    440,     1,         0,                                     35,                    155]
    FRONT_UPPER_LEG_RIGHT: [14,  239,    440,     -1,        0,                                     35,                    155]

    FRONT_LOWER_LEG_LEFT:  [2,   230,    276,     1,         0,                                     120,                   200]
    FRONT_LOWER_LEG_RIGHT: [13,  382,    306,     -1,        0,                                     120,                   200]

    BACK_BODY_LEFT:        [15,  306,    219,     1,         0,                                     90,                    135]
    BACK_BODY_RIGHT:       [0,   366,    222,     -1,        0,                                     90,                    135]

    BACK_UPPER_LEG_LEFT:   [14,  391,    440,     1,         0,                                     35,                    155]
    BACK_UPPER_LEG_RIGHT:  [1,   263,    440,     -1,        0,                                     35,                    155]

    BACK_LOWER_LEG_LEFT:   [13,  299,    288,     1,         0,                                     120,                   200]
    BACK_LOWER_LEG_RIGHT:  [2,   418,    288,     -1,        0,                                     120,                   200]

smov_states:  
  ros__parameters:
    # The values are in centimeters.
    upper_leg_length: 14.0
    lower_leg_length: 14.0
    hip_body_distance: 4.0
    reset_vals_after_state_pkg_ended: true
