motion_cmd:
  ros__parameters:
    update_rate_hz: 100.0
    use_imu: true
    imu_topic: "/bno085/imu"

    output_mode: "pwm"   # "pwm" (i2c_pwm_board) oder "states" (SMOV)

    # Dual-Board
    front_bus: 6   # Vorderbeine
    back_bus: 4    # Hinterbeine

    # Optional: SMOV States-Themen (falls output_mode="states")
    front_state_topic: "/smov/front_state"
    back_state_topic: "/smov/back_state"

    # Gait-Parameter
    gait:
      type: "dual_board_trot"
      stand_height_m: 0.155
      body_length_m: 0.186
      body_width_m: 0.078
      link_hip_m: 0.055
      link_upper_m: 0.1075
      link_lower_m: 0.130
      step_frequency_hz: 1.8
      step_height: 0.04
      max_stride: 0.08

    # Kanäle pro Board (je 6)
    channels_front: [0,1,2,  13,14,15]
    channels_back:  [0,1,2,  13,14,15]

    proportional_scale: 0.5
